---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
unzip( "activity.zip")
activity<- read.csv("activity.csv")
head(activity)
```

## What is mean total number of steps taken per day?
```{r}
totalstepsday  <- aggregate(data= activity,steps~date, sum, na.rm=TRUE)
head(totalstepsday)
```

```{r}
hist(totalstepsday$steps, main="Total number of steps", xlab="steps")
```

```{r}
mean(totalstepsday$steps)
median(totalstepsday$steps)
```

## What is the average daily activity pattern?

```{r}
stepsandinterval <- aggregate(steps ~ interval, activity, mean)
```

```{r}
plot(stepsandinterval, type='l')
```

```{r}
stepsandinterval$interval[which.max(stepsandinterval$steps)]
```


## Imputing missing values
Total number of missing values
```{r}
sum(is.na(activity$steps))
```

Filling missing values:

```{r}
activity2 <- merge(activity, totalstepsday, by="date", suffixes=c("", ".mean"))
onlynas <- is.na(activity2$steps)
activity2$steps[onlynas ] <- activity2$steps.mean[onlynas ]
activity2<- activity2[, c(1:3)]
head(activity2)
```

```{r}
totalstepsday2  <- aggregate(data= activity2,steps~date, sum, na.rm=TRUE)
head(totalstepsday2)
```

```{r}
hist(totalstepsday2$steps, main="Total number of steps no missing values", xlab="steps")
```

```{r}
mean(totalstepsday2$steps)
median(totalstepsday2$steps)
```

## Are there differences in activity patterns between weekdays and weekends?

